# Project : Product Return Prediction

## Introduction
In this project, we focus on understanding the reasons behind product returns and predict whether a product will be returned. Our primary goal is to provide actionable insights to retailers rather than achieving the maximum model accuracy. By identifying patterns and factors that leads to returns, we aim to help businesses to reduce return rates and associated costs.

## Problem Statement
To Predict the likelihood of a product being returned based on various features such as product category, price and customer demographics. The goal of this project is to provide insights into the factors that contribute to product returns, enabling reatilers to make informed decisions and improve their return policies and customer experience.

## Business Problem
In the retail industry, product returns are a significant challenge, impacting profitablity and customer satisfaction. Understanding the reasons behind returns can help retailers improve their products, services and customer experience.

## Mapping the Real-World Problem to a Machine Learning Problem
**It is a machine learning binary classification problem where we predict whether a order will be returned or not. By analyzing various order features, its aim to help businesses reduce return rates and improve customer satisfaction.**

### Import Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
import sklearn
from scipy import stats
import kaggle
from pathlib import Path
import sidetable

### Dispaly settings

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
#pd.set_option('display.max_info_rows', 1000)
pd.set_option('display.float_format', '{:.2f}'.format)
import warnings
warnings.filterwarnings('ignore')

### Data Ingestion and Exploration

In [3]:
path = Path.cwd()
paths = path.parent.joinpath('data','raw')

file = []
for p in paths.glob('*'):
    file.append(p.name)

print(file)

['.gitkeep', 'Global Superstore.xls']

In [4]:
#find all excel files name in .xls sheet
df = pd.read_excel(paths/'Global Superstore.xls',sheet_name=None)
df.keys()

dict_keys(['Orders', 'Returns', 'People'])

In [5]:
order_df = pd.read_excel(paths/'Global Superstore.xls',sheet_name='Orders')
return_df = pd.read_excel(paths/'Global Superstore.xls',sheet_name='Returns')
people_df = pd.read_excel(paths/'Global Superstore.xls',sheet_name='People')
display(order_df.tail(1),
    return_df.tail(1),
    people_df.tail(1))

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Postal Code,Market,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
51289,6147,MX-2012-134460,2012-05-22,2012-05-26,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,Nicaragua,NaN,LATAM,Central,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.38,3,0.00,1.80,0.00,High

     Returned        Order ID         Market
1172      Yes  CA-2014-168193  United States

                  Person          Region
12  Alejandro Ballentine  Southeast Asia

In [6]:
display('Orders shape :',order_df.shape, 
        'Returns shape', return_df.shape, 
        'People shape',people_df.shape)

'Orders shape :'

(51290, 24)

'Returns shape'

(1173, 3)

'People shape'

(13, 2)

In [20]:
# remove whitespaces from column names
dfs = [order_df, return_df, people_df]
for df in dfs:
    df.columns = df.columns.str.strip()

In [24]:
# Lets lower case all column names
dfs = [order_df, return_df, people_df]
for df in dfs:
    df.columns = df.columns.str.lower()

In [10]:
# lets check the data types of the columns
order_df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   row id          51290 non-null  int64
 1   order id        51290 non-null  object
 2   order date      51290 non-null  datetime64[ns]
 3   ship date       51290 non-null  datetime64[ns]
 4   ship mode       51290 non-null  object
 5   customer id     51290 non-null  object
 6   customer name   51290 non-null  object
 7   segment         51290 non-null  object
 8   city            51290 non-null  object
 9   state           51290 non-null  object
 10  country         51290 non-null  object
 11  postal code     9994 non-null   float64
 12  market          51290 non-null  object
 13  region          51290 non-null  object
 14  product id      51290 non-null  object
 15  category        51290 non-null  object
 16  sub-category    51290 non-null  object
 17  product name    51290 non-null  object
 18  sales           51290 non-null  float64
 19  quantity        51290 non-null  int64
 20  discount        51290 non-null  float64
 21  profit          51290 non-null  float64
 22  shipping cost   51290 non-null  float64
 23  order priority  51290 non-null  object
dtypes: datetime64[ns](2), float64(5), int64(2), object(15)
memory usage: 9.4+ MB

In [11]:
return_df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1173 entries, 0 to 1172
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   returned  1173 non-null   object
 1   order id  1173 non-null   object
 2   market    1173 non-null   object
dtypes: object(3)
memory usage: 27.6+ KB

In [12]:
people_df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   person  13 non-null     object
 1   region  13 non-null     object
dtypes: object(2)
memory usage: 340.0+ bytes

**Dataset Summary**

**The Global Superstore dataset contains three sheets: Orders, Returns and People.**
    
- **The Orders sheet contains information about customer orders, including order ID, customer ID, demographic details ,product details and sales data.**    
- **The Returns sheet contains information about returned orders, including order ID and market details.**    
- **The people sheet contains information about customers, including customer name and demographic details.**
    
**The data spans a robust four-year period from 2011 to 2015 . This dataset contains a vast array of order-related information, offering insights into retail operations across 147 countries.**

Brief description of columns:

- **Order ID**: Unique identifier for each order.

- **Order Date**: The date when the order was placed. 

- **Ship Date**: The date when the order was shipped. 

- **Ship Mode**: The day order was shipped (e.g., First Class, Second Class, Standard Class, Same Day).

- **Customer ID**: Unique identifier for each customer. 

- **Customer Name**: The name of the customer. 

- **Segment**: The business segment (e.g., Consumer, Corporate, Home Office). 

- **City**: The city where the order was placed.

- **State**: The state where the order was placed.

- **Country**: The country where the order was placed.

- **Postal Code**: The postal code of the order's location.

- **Market**: The region where the sale took place (e.g., APAC, EMEA). 

- **Region**: The specific geographical region (e.g., Central, East). 

- **Product ID**: Unique identifier for each product.

- **Product Category**: The category of products (e.g., Furniture, Technology, Office Supplies). 

- **Product Sub-Category**: More specific product grouping (e.g., Chairs, Phones). 

- **Sales**: The total sales value of the order. 

- **Quantity**: Quantity of products sold. 

- **Discount**: Discount applied to the product. 

- **Profit**: The profit earned from the order. 

- **Shipping Cost**: The cost incurred to ship the product.

## **Number Formatting and Category Consistency**

In [13]:
dtype_df = pd.DataFrame({
    'dtype': order_df.dtypes,
    'nunique': order_df.nunique(),
    'unique' : [order_df[col].unique() for col in order_df.columns]
}, index=order_df.columns)
dtype_df

,dtype,nunique,unique
row id,int64,51290,"[32298, 26341, 25330, 13524, 47221, 22732, 305..."
order id,object,25035,"[CA-2012-124891, IN-2013-77878, IN-2013-71249,..."
order date,datetime64[ns],1430,"[2012-07-31 00:00:00, 2013-02-05 00:00:00, 201..."
ship date,datetime64[ns],1464,"[2012-07-31 00:00:00, 2013-02-07 00:00:00, 201..."
ship mode,object,4,"[Same Day, Second Class, First Class, Standard..."
customer id,object,1590,"[RH-19495, JR-16210, CR-12730, KM-16375, RH-94..."
customer name,object,795,"[Rick Hansen, Justin Ritter, Craig Reiter, Kat..."
segment,object,3,"[Consumer, Corporate, Home Office]"
city,object,3636,"[New York City, Wollongong, Brisbane, Berlin, ..."
state,object,1094,"[New York, New South Wales, Queensland, Berlin..."
country,object,147,"[United States, Australia, Germany, Senegal, N..."
postal code,float64,631,"[10024.0, nan, 95823.0, 28027.0, 22304.0, 4242..."
market,object,7,"[US, APAC, EU, Africa, EMEA, LATAM, Canada]"
region,object,13,"[East, Oceania, Central, Africa, West, South, ..."
product id,object,10292,"[TEC-AC-10003033, FUR-CH-10003950, TEC-PH-1000..."
category,object,3,"[Technology, Furniture, Office Supplies]"
sub-category,object,17,"[Accessories, Chairs, Phones, Copiers, Tables,..."
product name,object,3788,[Plantronics CS510 - Over-the-Head monaural Wi...
sales,float64,27200,"[2309.65, 3709.3949999999995, 5175.17100000000..."
quantity,int64,14,"[7, 9, 5, 8, 4, 6, 13, 12, 14, 10, 2, 11, 3, 1]"
discount,float64,29,"[0.0, 0.1, 0.2, 0.4, 0.15, 0.3, 0.5, 0.17, 0.4..."
profit,float64,28234,"[762.1844999999998, -288.765, 919.970999999999..."
shipping cost,float64,17095,"[933.57, 923.63, 915.49, 910.16, 903.04, 897.3..."
order priority,object,4,"[Critical, Medium, High, Low]"

In [14]:
def highlight_zero_neg(val):
    if val == 0:
        return 'background-color: yellow; color: black'   # zero values highlighted in yellow
    elif val < 0:
        return 'background-color: red; color: white'    # negative values highlighted in red
    else:
        return ''  # no highlight for positive values

In [15]:
# Number Formatting and data description for numerical columns
df_desc = order_df.describe(exclude='object')
display(df_desc.style.applymap(highlight_zero_neg, subset = df_desc.select_dtypes(include='number').columns))

In [16]:
def highlight_repeats(series, min_repeats):
    counts = series.value_counts()
    repeated_values = counts[counts >= min_repeats].index
    return series.apply(lambda x: 'background-color: green; color:white' if x in repeated_values else '')

In [17]:
df_desc.style.apply(highlight_repeats, min_repeats=2, subset=df_desc.select_dtypes(exclude='object').iloc[:,1:].columns)

**NOTEs**:
- **Discount**: The discount column has a lot of zero values, which might indicate that many orders were made without any discount. Or, there is any other reason we need to investigate furthur.
- **Profit**: The profit column has a negative value which indicates that there are some orders that resulted in a loss and profit value is zero as well which inidicates that there are some orders that did not generate any profit, or these values are some error need to investigate furthur.

In [18]:
order_df.describe(include='object')

,order id,ship mode,customer id,customer name,segment,city,state,country,market,region,product id,category,sub-category,product name,order priority
count,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290
unique,25035,4,1590,795,3,3636,1094,147,7,13,10292,3,17,3788,4
top,CA-2014-100111,Standard Class,PO-18850,Muhammed Yedwab,Consumer,New York City,California,United States,APAC,Central,OFF-AR-10003651,Office Supplies,Binders,Staples,Medium
freq,14,30775,97,108,26518,915,2001,9994,11002,11117,35,31273,6152,227,29433

In [ ]:
cat_df = order_df.select_dtypes(include='object')
cat_df.stb.freq(['country','region','segment','city', 'state', 'market'])

                               country          region      segment  \
0                        United States            East     Consumer
1                        United States            West     Consumer
2                        United States            East     Consumer
3                        United States            East    Corporate
4                        United States            West     Consumer
5                   Dominican Republic       Caribbean     Consumer
6                        United States            West    Corporate
7                        United States            West     Consumer
8                          Philippines  Southeast Asia     Consumer
9                        United States         Central     Consumer
10                       United States            East    Corporate
11                       United States         Central     Consumer
12                           Indonesia  Southeast Asia     Consumer
13                           Nicaragua         Central     Consumer
14                            Honduras         Central     Consumer
15                              Turkey            EMEA     Consumer
16                             Nigeria          Africa     Consumer
17                       United States            West    Corporate
18                              Mexico           North     Consumer
19                            Thailand  Southeast Asia     Consumer
20                       United States            East  Home Office
21                               Egypt          Africa     Consumer
22                           Australia         Oceania     Consumer
23                       United States            West  Home Office
24                           Australia         Oceania     Consumer
25                         Philippines  Southeast Asia    Corporate
26                         El Salvador         Central     Consumer
27                             Germany         Central     Consumer
28                      United Kingdom           North     Consumer
29                       United States            West    Corporate
30    Democratic Republic of the Congo          Africa     Consumer
31                           Nicaragua         Central    Corporate
32                           Indonesia  Southeast Asia    Corporate
33                           Australia         Oceania     Consumer
34                             Nigeria          Africa    Corporate
35                            Honduras         Central    Corporate
36                           Argentina           South     Consumer
37                             Austria         Central     Consumer
38                              Mexico           North    Corporate
39                  Dominican Republic       Caribbean  Home Office
40                       United States            West     Consumer
41                              France         Central     Consumer
42                  Dominican Republic       Caribbean    Corporate
43                              Turkey            EMEA    Corporate
44                           Australia         Oceania     Consumer
45                       United States         Central    Corporate
46                            Honduras         Central     Consumer
47                           Singapore  Southeast Asia     Consumer
48                                Iraq            EMEA     Consumer
49                       United States            West  Home Office
50                         Philippines  Southeast Asia  Home Office
51                       United States            East  Home Office
52                       United States            West  Home Office
53                            Honduras         Central  Home Office
54                               Spain           South     Consumer
55                           Australia         Oceania    Corporate
56                           Australia         Oceania     Consumer
57                      United Kingdom           North    Corporate
58                             Nigeria          Africa     Consumer
59                            Thailand  Southeast Asia    Corporate
60                              Panama         Central     Consumer
61                             Vietnam  Southeast Asia     Consumer
62                           Australia         Oceania    Corporate
63                           Australia         Oceania     Consumer
64                       United States         Central    Corporate
65                           Australia         Oceania     Consumer
66                           Australia         Oceania     Consumer
67                       United States         Central     Consumer
68                              Mexico           North     Consumer
69                           Guatemala         Central     Consumer
70                              Brazil           South     Consumer
71                           Australia         Oceania     Consumer
72                       United States            East     Consumer
73                        Saudi Arabia            EMEA     Consumer
74                             Germany         Central     Consumer
75                       United States         Central  Home Office
76                     Myanmar (Burma)  Southeast Asia     Consumer
77                           Indonesia  Southeast Asia     Consumer
78                               Italy           South     Consumer
79                              Panama         Central    Corporate
80                             Morocco          Africa     Consumer
81                       United States         Central     Consumer
82                         El Salvador         Central    Corporate
83                             Nigeria          Africa  Home Office
84                         New Zealand         Oceania     Consumer
85                           Australia         Oceania    Corporate
86                               Egypt          Africa     Consumer
87                             Germany         Central    Corporate
88                       United States         Central  Home Office
89                            Thailand  Southeast Asia  Home Office
90                             Senegal          Africa     Consumer
91                         El Salvador         Central     Consumer
92                           Guatemala         Central     Consumer
93                         El Salvador         Central     Consumer
94                           Nicaragua         Central  Home Office
95                              Mexico           North     Consumer
96                        South Africa          Africa     Consumer
97                                Cuba       Caribbean     Consumer
98                              Panama         Central     Consumer
99                        Saudi Arabia            EMEA    Corporate
100                               Peru           South     Consumer
101                          Indonesia  Southeast Asia  Home Office
102                           Colombia           South     Consumer
103                            Vietnam  Southeast Asia  Home Office
104                               Iraq            EMEA    Corporate
105                          Indonesia  Southeast Asia     Consumer
106                              Egypt          Africa  Home Office
107                          Argentina           South    Corporate
108                      United States         Central    Corporate
109                           Pakistan    Central Asia     Consumer
110                             Mexico           North     Consumer
111                              Egypt          Africa    Corporate
112                         Bangladesh    Central Asia     Consumer
113                            Austria         Central    Corporate
114                          Australia         Oceania    Corporate
115                          Australia         Oceania    Corporate
116                     United Kingdom           North  Home Office
117                             Turkey            EMEA  Home Office
118                             Turkey            EMEA     Consumer
119                             Mexico           North     Consumer
120                          Australia         Oceania    Corporate
121                             France         Central     Consumer
122                          Australia         Oceania    Corporate
123                        South Korea      North Asia     Consumer
124                          Australia         Oceania  Home Office
125                          Australia         Oceania    Corporate
126                          Australia         Oceania     Consumer
127                     United Kingdom           North     Consumer
128                              Italy           South     Consumer
129                            Ireland           North     Consumer
130                          Indonesia  Southeast Asia     Consumer
131                              Haiti       Caribbean     Consumer
132                            Germany         Central     Consumer
133                             Sweden           North    Corporate
134                              Spain           South    Corporate
135                    Myanmar (Burma)  Southeast Asia    Corporate
136                             France         Central    Corporate
137                              Chile           South     Consumer
138                             Brazil           South    Corporate
139                             Turkey            EMEA     Consumer
140                             Sweden           North     Consumer
141                            Vietnam  Southeast Asia    Corporate
142                       Saudi Arabia            EMEA     Consumer
143                             Angola          Africa     Consumer
144                      United States            West    Corporate
145                               Cuba       Caribbean    Corporate
146                            Austria         Central  Home Office
147                          Australia         Oceania  Home Office
148                             Mexico           North     Consumer
149                        El Salvador         Central    Corporate
150                              China      North Asia     Consumer
151                          Indonesia  Southeast Asia    Corporate
152                           Honduras         Central    Corporate
153   Democratic Republic of the Congo          Africa    Corporate
154                          Indonesia  Southeast Asia    Corporate
155                       South Africa          Africa     Consumer
156                             Mexico           North  Home Office
157                             Mexico           North     Consumer
158                          Guatemala         Central  Home Office
159                          Guatemala         Central    Corporate
160                          Indonesia  Southeast Asia    Corporate
161                              Ghana          Africa     Consumer
162                        El Salvador         Central     Consumer
163                      Cote d'Ivoire          Africa     Consumer
164                          Australia         Oceania  Home Office
165                          Australia         Oceania     Consumer
166                          Australia         Oceania     Consumer
167                              Spain           South  Home Office
168                          Nicaragua         Central     Consumer
169                        New Zealand         Oceania     Consumer
170                             Mexico           North     Consumer
171                          Indonesia  Southeast Asia     Consumer
172                             France         Central  Home Office
173                             France         Central     Consumer
174                 Dominican Republic       Caribbean     Consumer
175                          Australia         Oceania    Corporate
176                           Tanzania          Africa     Consumer
177                              Spain           South     Consumer
178                             Mexico           North     Consumer
179                               Iraq            EMEA     Consumer
180                               Iran            EMEA     Consumer
181                            Germany         Central    Corporate
182                               Cuba       Caribbean     Consumer
183                          Australia         Oceania    Corporate
184                           Pakistan    Central Asia    Corporate
185                          Indonesia  Southeast Asia     Consumer
186                            Germany         Central     Consumer
187                          Australia         Oceania     Consumer
188                          Australia         Oceania     Consumer
189                      United States           South     Consumer
190                      United States         Central    Corporate
191                              Sudan          Africa     Consumer
192                            Morocco          Africa     Consumer
193                              Italy           South    Corporate
194                          Indonesia  Southeast Asia     Consumer
195                        El Salvador         Central     Consumer
196                               Cuba       Caribbean     Consumer
197                      United States           South    Corporate
198                             Panama         Central  Home Office
199                             Panama         Central    Corporate
200                            Morocco          Africa     Consumer
201                           Honduras         Central  Home Office
202                            Germany         Central  Home Office
203                      United States            West     Consumer
204                      United States            East    Corporate
205                             Turkey            EMEA    Corporate
206                        Netherlands         Central     Consumer
207                        El Salvador         Central  Home Office
208                              Egypt          Africa    Corporate
209                 Dominican Republic       Caribbean    Corporate
210                             Brazil           South     Consumer
211                      United States           South     Consumer
212                      United States         Central     Consumer
213                       South Africa          Africa    Corporate
214                               Peru           South    Corporate
215                        New Zealand         Oceania    Corporate
216                            Morocco          Africa    Corporate
217                              Italy           South     Consumer
218                              India    Central Asia     Consumer
219                              China      North Asia     Consumer
220                          Australia         Oceania  Home Office
221                            Vietnam  Southeast Asia     Consumer
222                      United States           South     Consumer
223                             Sweden           North  Home Office
224                       Saudi Arabia            EMEA    Corporate
225                            Morocco          Africa  Home Office
226                             Mexico           North    Corporate
227                             Mexico           North     Consumer
228                             Mexico           North     Consumer
229                              India    Central Asia     Consumer
230                           Honduras         Central     Consumer
231                              Haiti       Caribbean    Corporate
232                          Guatemala         Central     Consumer
233                            Nigeria          Africa     Consumer
234                            Nigeria          Africa     Consumer
235                             Mexico           North    Corporate
236                              India    Central Asia     Consumer
237                            Germany         Central     Consumer
238                             France         Central    Corporate
239   Democratic Republic of the Congo          Africa  Home Office
240                              China      North Asia    Corporate
241                         Bangladesh    Central Asia    Corporate
242                          Australia         Oceania  Home Office
243                            Algeria          Africa     Consumer
244                             Turkey            EMEA     Consumer
245                             Turkey            EMEA     Consumer
246                        New Zealand         Oceania    Corporate
247                             Mexico           North    Corporate
248                            Germany         Central     Consumer
249                           Cambodia  Southeast Asia     Consumer
250                          Nicaragua         Central     Consumer
251                             Mexico           North    Corporate
252                              Japan      North Asia     Consumer
253                               Iran            EMEA    Corporate
254                           Honduras         Central     Consumer
255                             Brazil           South  Home Office
256                      United States            West     Consumer
257                      United States           South    Corporate
258                      United States            East    Corporate
259                      United States            East     Consumer
260                      United States         Central  Home Office
261                      United States         Central    Corporate
262                       South Africa          Africa     Consumer
263                          Singapore  Southeast Asia    Corporate
264                        Philippines  Southeast Asia     Consumer
265                        New Zealand         Oceania     Consumer
266                             Mexico           North    Corporate
267                             Mexico           North     Consumer
268                              Italy           South  Home Office
269                              Italy           South     Consumer
270                               Iraq            EMEA     Consumer
271                          Guatemala         Central     Consumer
272                            Germany         Central     Consumer
273                        El Salvador         Central     Consumer
274                 Dominican Republic       Caribbean     Consumer
275                               Cuba       Caribbean    Corporate
276                              China      North Asia    Corporate
277                           Bulgaria            EMEA     Consumer
278                          Australia         Oceania  Home Office
279                          Australia         Oceania  Home Office
280                      United States           South    Corporate
281                      United States           South     Consumer
282                             Turkey            EMEA    Corporate
283                        South Korea      North Asia  Home Office
284                       South Africa          Africa    Corporate
285                       Saudi Arabia            EMEA  Home Office
286                             Mexico           North    Corporate
287                             Mexico           North     Consumer
288                             Mexico           North     Consumer
289                               Iraq            EMEA  Home Office
290                          Indonesia  Southeast Asia     Consumer
291                              India    Central Asia    Corporate
292                            Hungary            EMEA     Consumer

### **Missing Value Analysis**

In [27]:
missing_df = order_df.stb.missing()
missing_df

                missing  total  percent
postal code       41296  51290    80.51
row id                0  51290     0.00
region                0  51290     0.00
order priority        0  51290     0.00
shipping cost         0  51290     0.00
profit                0  51290     0.00
discount              0  51290     0.00
quantity              0  51290     0.00
sales                 0  51290     0.00
product name          0  51290     0.00
sub-category          0  51290     0.00
category              0  51290     0.00
product id            0  51290     0.00
market                0  51290     0.00
order id              0  51290     0.00
country               0  51290     0.00
state                 0  51290     0.00
city                  0  51290     0.00
segment               0  51290     0.00
customer name         0  51290     0.00
customer id           0  51290     0.00
ship mode             0  51290     0.00
ship date             0  51290     0.00
order date            0  51290     0.00
difference            0  51290     0.00